from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 50, 691, 61))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")

        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(80, 140, 1100, 500))
        self.imageLabel.setStyleSheet("border:1px solid red")
        self.imageLabel.setObjectName("imageLabel")

        self.bgImage = QPixmap('bgImage.jpg')
        self.imageLabel.setPixmap(self.bgImage)

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1281, 741))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(490, 20, 421, 61))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 190, 521, 351))
        self.label_3.setStyleSheet("border: 1px solid rgb(0, 85, 255)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(700, 190, 521, 351))
        self.label_4.setStyleSheet("border: 1px solid rgb(0, 85, 255)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 580, 361, 91))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 580, 361, 91))
        self.pushButton_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1281, 751))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 90, 381, 91))
        self.pushButton_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 90, 381, 91))
        self.pushButton_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 280, 381, 91))
        self.pushButton_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(730, 270, 381, 91))
        self.pushButton_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1291, 731))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(460, 30, 321, 71))
        self.label_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(40, 210, 561, 361))
        self.label_6.setStyleSheet("border: 1px solid red")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(670, 210, 561, 361))
        self.label_7.setStyleSheet("border: 1px solid red")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 600, 391, 81))
        self.pushButton_7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(760, 600, 391, 81))
        self.pushButton_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1287, 31))
        self.menubar.setObjectName("menubar")

        # Add mainmenu option
        self.mainMenu = QtWidgets.QMenu(self.menubar)
        self.mainMenu.setObjectName("mainMenu")

        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuText = QtWidgets.QMenu(self.menubar)
        self.menuText.setObjectName("menuText")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Initialize options for mainMenu
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.actionFace_Detection = QtWidgets.QAction(MainWindow)
        self.actionFace_Detection.setObjectName("actionFace_Detection")
        self.actionObject_Detection = QtWidgets.QAction(MainWindow)
        self.actionObject_Detection.setObjectName("actionObject_Detection")
        self.actionDigit_Recognition = QtWidgets.QAction(MainWindow)
        self.actionDigit_Recognition.setObjectName("actionDigit_Recognition")
        self.actionText_Summarizer = QtWidgets.QAction(MainWindow)
        self.actionText_Summarizer.setObjectName("actionText_Summarizer")
        self.actionSenitment_Analysis = QtWidgets.QAction(MainWindow)
        self.actionSenitment_Analysis.setObjectName("actionSenitment_Analysis")
        self.actionText_Classification = QtWidgets.QAction(MainWindow)
        self.actionText_Classification.setObjectName("actionText_Classification")

        # Add options inside main menu
        self.mainMenu.addAction(self.actionHome)
        self.mainMenu.addAction(self.actionExit)

        self.menuOptions.addAction(self.actionFace_Detection)
        self.menuOptions.addAction(self.actionObject_Detection)
        self.menuOptions.addAction(self.actionDigit_Recognition)
        self.menuText.addAction(self.actionText_Summarizer)
        self.menuText.addAction(self.actionSenitment_Analysis)
        self.menuText.addAction(self.actionText_Classification)

        # Add mainMenu to our menubar
        self.menubar.addAction(self.mainMenu.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuText.menuAction())

        self.frame.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Machine Learning Applications"))
        self.label_2.setText(_translate("MainWindow", "Face Detection"))
        self.pushButton.setText(_translate("MainWindow", "Upload Image"))
        self.pushButton_2.setText(_translate("MainWindow", "Detect Faces"))
        self.pushButton_3.setText(_translate("MainWindow", "Live Face Detection"))
        self.pushButton_4.setText(_translate("MainWindow", "Number Plate Detection"))
        self.pushButton_5.setText(_translate("MainWindow", "Pedestarian Detection"))
        self.pushButton_6.setText(_translate("MainWindow", "Other Objects Detection"))
        self.label_5.setText(_translate("MainWindow", "Digit Recognition"))
        self.pushButton_7.setText(_translate("MainWindow", "Upload Digit"))
        self.pushButton_8.setText(_translate("MainWindow", "Recognize Digit"))
        self.mainMenu.setTitle(_translate("MainWindow", "Main"))
        self.menuOptions.setTitle(_translate("MainWindow", "Image"))
        self.menuText.setTitle(_translate("MainWindow", "Text"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFace_Detection.setText(_translate("MainWindow", "Face Detection"))
        self.actionObject_Detection.setText(_translate("MainWindow", "Object Detection"))
        self.actionDigit_Recognition.setText(_translate("MainWindow", "Digit Recognition"))
        self.actionText_Summarizer.setText(_translate("MainWindow", "Text Summarizer"))
        self.actionSenitment_Analysis.setText(_translate("MainWindow", "Senitment Analysis"))
        self.actionText_Classification.setText(_translate("MainWindow", "Text Classification"))

        self.actionHome.triggered.connect(self.showHome)
        self.actionFace_Detection.triggered.connect(self.showFaceDetection)

        self.pushButton.clicked.connect(self.uploadImage)

    def showHome(self):
        self.frame.hide()

    def showFaceDetection(self):
        self.frame.show()
        self.frame_2.hide()

    def uploadImage(self):
        file = QtWidgets.QFileDialog.getOpenFileName()
        # print(file)
        self.img_1 = QPixmap(file[0])
        self.img_1 = self.img_1.scaledToHeight(self.label_3.height())
        self.img_1 = self.img_1.scaledToWidth(self.label_3.width())
        self.label_3.setPixmap(self.img_1)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

